Resources:
  EncryptedBucket:
    Type: AWS::S3::Bucket

  DecryptedBucket:
    Type: AWS::S3::Bucket

  DecryptorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: decryptor
      Runtime: nodejs12.x
      Handler: index.handler
      Role: arn:aws:iam::642744795524:role/lambda-s3-role
      Code:
        S3Bucket: arn:aws:s3:::decryptor-deploy-bucket
        S3Key: decryptor.zip

  KeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: decryptor-key-table
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2