Resources:
  EncryptedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: decryptor-encrypted-files
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event: s3:ObjectCreated:Put
            Function: arn:aws:lambda:us-east-1:642744795524:function:decryptor

  DecryptedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: decryptor-decrypted-files

  DecryptorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: decryptor
      Runtime: nodejs14.x
      Handler: index.handler
      Role: arn:aws:iam::642744795524:role/lambda-s3-role
      Code:
        S3Bucket: decryptor-deploy-bucket
        S3Key: decryptor.zip

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: decryptor
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::decryptor-encrypted-files
      SourceAccount: 642744795524

  DecryptorKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: decryptor-key-table
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2